@startuml

package "app.models.schemas" {
    class ConversionRequest {
        + amount_cop : float
        + exchange_rate : float
        + target_currency : str
    }
}

package "app.db.connection" {
    class DatabaseManager << (M, #FF7000) Module >> {
        + init_db() : void
        + insert_conversion(amount_cop, exchange_rate, total_usd, target_currency) : void
        + get_all_history() : list
    }
}

package "main" {
    class FastAPI_App << (A, #00A3A3) Application >> {
        + app : FastAPI
        + startup_event() : void
        + read_root() : dict
        + convert_currency(data: ConversionRequest) : dict
        + read_history() : dict
    }
}

FastAPI_App ..> ConversionRequest : "Valida datos de entrada con"
FastAPI_App --> DatabaseManager : "Llama funciones de"

@endum



@startuml Diagrama_clases_API_GlobalSettler{
package "app.models.schemas"
    class ConversionRequest{
        amount_cop: float
        exchange_rate: float
        target_currency: string
    }
}    

package "database(connection.py)"{
    class DBConnection{
        get_db_connection(): MYSQLConnection
        init_db(): void
        insert_conversion(amount_cop, exchange_rate,total_usd,target_currency): void
        get_all_history(): list
    }
}

package "API Routes (main.py)"{
    class API_Endpoints {
        read:root(): dict
        convert_currency(data: ConversionRequest): dict
        get_conversion_history(): dict
    }
}


ConversionRequest.down.> API_Endpoints : "Usar como entrada"
API_Endpoints -down-> DBConnection : "Llama funciones de persistencia"

@enduml


